version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    target-branch: "master"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"